### ISSUE TITLE
When open large image for bursting, the entire image should be shown.

### ISSUE THREAD

**Issue by wlin98004** [stamp-web/stamp-imageparsing#77]
When open an image with "high" resolution, the initial view of the image is cut off.  It will be nice that we fit the image in the app screen.  

Here is a sample.  Original image looks like

![image3](https://user-images.githubusercontent.com/16296857/188034163-87d301b9-3ec3-4038-9366-0a1f7a7ba728.jpg)

Here is how it is opened in the app.

![image](https://user-images.githubusercontent.com/16296857/188034290-bd1471df-a112-43ed-8e9f-7f795e163a91.png)

**Comment by jadrake75** [comment]
This is strange.  This is what I see 

![image](https://user-images.githubusercontent.com/3221886/188040307-cbecb929-4fbd-4054-b34d-e97cfcbe92af.png)

This might be a simple CSS issue.  it is strange how it is cutting it off.  If you hit F-12 it will open the Chrome Dev Tools and you can go to Elements and select the photo.  This is a <canvas> object.  I noticed if I add Width: 100% to the element filters it does stretch to the edge

![image](https://user-images.githubusercontent.com/3221886/188040538-8c259e89-fdfa-4a7c-93ff-1c0f33109244.png)

**Comment by jadrake75** [comment]
Actually this won't work since the ZOOM in and out is predicated on being able to adjust the image.  Still .... I am not sure why your canvas is for some reason getting cut off.  You can see mine is not, but I still have the area blank on the right, but the image is "complete".  So something to play with here.  What resolution is your monitor?

**Comment by wlin98004** [comment]
Actually I may not have attached the original file.  Try to burst this one and see if you still have the issue or not.  The original file resolution is 1600x1305.

![image3](https://user-images.githubusercontent.com/16296857/188204332-6957c97e-872e-4c2f-8638-a4abd4470eb7.jpg)

**Comment by jadrake75** [comment]
opens no problem for me

**Comment by wlin98004** [comment]
I spent sometime on this.  I found the repro.  You need to open up an image first and then open up a different image with a different size.  The canvas size is not reset according to the new image.  It still have the old width and height from the last image.  

I also recommend we should fit the image in the canvas according to its width or height which ever is longer.  This way, the entire image will be shown when we load the image.

**Comment by jadrake75** [comment]
This is maybe not as easy as you think since I am using a canvas control which needs to be manipulated with a zoom factor.  We also need to track everything since the burst images are derived FROM the image in the canvas so accuracy matters.  However feel free to investigate

**Comment by jadrake75** [comment]
Fixed with wlin-77
