### ISSUE TITLE
File is not saved to the selected target folder without selecting a sub folder.

### ISSUE THREAD

**Issue by wlin98004** [stamp-web/stamp-imageparsing#80]
When I first use the stamp burst program, I wasn't able to find the output file.  It turned out you need to have a sub folder selected.  If there is no sub folder,  the output file is saved in the web-app/platform folder.  Most of the user will not know this.  If no sub folder is selected, the file should just be saved to the selected target folder.

Also recommend to rename the Folder option in the region to "Target Sub Folder".

![image](https://user-images.githubusercontent.com/16296857/190087703-36f62a82-7ed9-4a83-ab15-8c307e869d60.png)

Here are some more minor issues:

- Simply switching the target folder will not save burst image to new location.  There must be some other change to trigger the new target folder to be in effect.
- If there are multiple sub folders, saving a region will always revert the sub folder back to the first option.

**Comment by jadrake75** [comment]
ok, I have posted the fix.  See https://github.com/stamp-web/stamp-imageparsing/commit/0b2dc1f942ba978dd10dd974f6b1f40c8f5dfcb5

**Comment by jadrake75** [comment]
Closed with PR
